<a href="https://colab.research.google.com/github/rtuscdawww/DoAnMonHoc/blob/main/lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('2274802010148 - Đặng Thị Trúc Đào')

2274802010148 - Đặng Thị Trúc Đào


In [ ]:
#Câu 1
print('Câu 1')
from scipy import linalg # Tải gói linalg của scipy vào bộ nhớ (để sử dụng)
import numpy as np # Tải gói numpy vào sử dụng với tên gọi là np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0).
print(f'Kết quả của 3, k=1 là : {F}')
F1 = np.eye(3, k=0)
print(f'Kết quả của 3, k=0 là : {F1}')
F2 = np.eye(3, k=-1)
print(f'Kết quả của 3, k=-1 là : {F2}')
print('Xem hạng ma trận:')
Hang = np.linalg.matrix_rank(C)
print(Hang)
print('Tính ma trận nghịch đảo:')
print(A.I)
linalg.inv(A) # đây là lệnh của gói scipy, nên có thể sử dụng scipy.linalg.inv(A)
print('Định thức ma trận:')
dinhthuc = linalg.det(A)
print(dinhthuc)
print('Chuyển đổi ma trận:')
dong_cot = A.T
print(f'dòng thành cột: {dong_cot}')
vi_lien_hop = A.H
print(f'Chuyển vị liên hợp: {vi_lien_hop}')
print('Giải các loại phương trình tuyến tính:')
pttt_1 = linalg.solve(A, b)
print(pttt_1)
E = np.asmatrix(a).T
print(E)
pttt_2 = linalg.lstsq(F, E)
print(pttt_2)
print('Các hàm trên ma trận:')
print('Cộng ma trận:')
cong = np.add(A,D)
print(cong)
print('Trừ ma trận:')
tru = np.subtract(A,D)
print(tru)
print('Chia ma trận:')
chia = np.divide(A,D)
print(chia)
print('Nhân ma trận:')
nhan = np.dot(A,D)
nhan1 = A@D
nhan2 = np.multiply(D,A)
nhan3 = np.vdot(A,D)
print(nhan)
print(nhan1)
print(nhan2)
print(nhan3)
print('Hàm lũy thừa và logarith ma trận:')
luythua = linalg.expm(A)
print(luythua)
logarith = linalg.logm(A)
print(logarith)

Câu 1
Kết quả của 3, k=1 là : [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
Kết quả của 3, k=0 là : [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Kết quả của 3, k=-1 là : [[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
Xem hạng ma trận:
5
Tính ma trận nghịch đảo:
[[-3.77942477  6.94675644]
 [ 2.31010029 -2.06388078]]
Định thức ma trận:
-0.12125001179059523
Chuyển đổi ma trận:
dòng thành cột: [[0.25024557 0.28009969]
 [0.8422943  0.4582553 ]]
Chuyển vị liên hợp: [[0.25024557 0.28009969]
 [0.8422943  0.4582553 ]]
Giải các loại phương trình tuyến tính:
[[-3.77942477 -6.22779722j  0.        +27.17493264j
   0.        +30.34226431j]
 [ 2.31010029+12.53537945j  0.         -5.69920334j
   0.         -5.45298384j]]
[[1]
 [2]
 [3]]
(array([[0.],
       [1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))
Các hàm trên ma trận:
Cộng ma trận:
[[4.25024557 3.8422943 ]
 [2.28009969 6.4582553 ]]
Trừ ma trận:
[[-3.74975443 -2.1577057 ]
 [-1.71990031 -5.5417447 ]]
Chia ma trận:
[[0.06256139 0.28076477]
 [0.140049

In [ ]:
#Câu 2.3 Ma trận hội tụ
print('Ma trận phân kỳ:')
import numpy as np
print('Tính ma trận A')
A = np.array([[0,1],[1,0]])
print(A)
temp = A.dot(A) #tính toán lần 1
print(temp)
k = 6
for i in range(k-1):
  temp = temp.dot(A)
  print(temp)
  print('---')
print('Tính ma trận B')
B = np.array([[0,-1],[-1,0]])
print(B)
temp = B.dot(B)
print(temp)
k = 5
for i in range(k-1):
  temp = temp.dot(B)
  print(temp)
  print('---')
print('Ma trận hội tụ')
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)
temp = C.dot(C) # tính toan lần thứ 1
print(temp)
k= 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)
k = 1000
for i in range(k-1):
  temp = temp.dot(C)
print(temp)

Ma trận phân kỳ:
Tính ma trận A
[[0 1]
 [1 0]]
[[1 0]
 [0 1]]
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
Tính ma trận B
[[ 0 -1]
 [-1  0]]
[[1 0]
 [0 1]]
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
Ma trận hội tụ
[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]
[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]
[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Câu 2.4 Ma trận Markov
print('Câu 2.4 - 1')
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MM = M.dot(M) # tính M3
print (MM)
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

Câu 2.4 - 1
[[0.7  0.45]
 [0.3  0.55]]
[[0.7  0.45]
 [0.3  0.55]]
[[0.6 0.6]
 [0.4 0.4]]


In [ ]:
print('Câu 2.4 - 2')
M = np.array([ [0.5, 0.5], [0.5, 0.5]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM)
MM = M.dot(M) # tính M3
print (MM)
for i in range(100): # tính các M^ khác.
 MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

Câu 2.4 - 2
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]
[[0.5 0.5]
 [0.5 0.5]]


In [ ]:
print('Câu 3.2')
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U
print (P)
print (L)
print (U)
L.dot(U)


Câu 3.2
[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]


array([[0.8, 0.3],
       [0.2, 0.7]])

In [ ]:
print('Câu 4.1')
import numpy as np
A = np.array([17, 34, 5])
B = np.array([[1, -2, 2], [-1, 1, 3], [1, -1, -4]])
AB = np.dot(A,B)
print("Kết quả 3:")
print(AB)

C = np.array([0, 6, 26])
CB = np.dot(C,B)
print('Kết quả 4:')
print(CB)

E = np.array([33, 0, 14])
EB = np.dot(E,B)
print('Kết quả 5:')
print(EB)

G = np.array([12, 9, 34])
GB = np.dot(G,B)
print('Kết quả 6:')
print(GB)

D = np.array([25, 35, 35])
DB = np.dot(D,B)
print('Kết quả 7:')
print(DB)

inv_B = np.linalg.inv(B)
print(f'Ma trận nghịch đảo của B là: \n {inv_B}')
print('Phục hồi các kết quả là: ')
kq3 = np.dot(AB,inv_B)
print(kq3)
kq4 = np.dot(CB,inv_B)
print(kq4)
kq5 = np.dot(EB,inv_B)
print(kq5)
kq6 = np.dot(GB,inv_B)
print(kq6)
kq7 = np.dot(DB,inv_B)
print(kq7)

Câu 4.1
Kết quả 3:
[-12  -5 116]
Kết quả 4:
[ 20 -20 -86]
Kết quả 5:
[ 47 -80  10]
Kết quả 6:
[ 37 -49 -85]
Kết quả 7:
[ 25 -50  15]
Ma trận nghịch đảo của B là: 
 [[ -1. -10.  -8.]
 [ -1.  -6.  -5.]
 [ -0.  -1.  -1.]]
Phục hồi các kết quả là: 
[17. 34.  5.]
[ 0.  6. 26.]
[33.  0. 14.]
[12.  9. 34.]
[25. 35. 35.]


In [ ]:
print('Câu 5')
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = A^2
print(f'Kết quả A^2 là : \n {temp}')
temp = temp.dot(A) # lúc này temp = A^3
print(f'Kết quả của A^3 là: \n {temp}')

A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
  temp = temp.dot(A)
  sumA = sumA + temp
print(temp)
print(f'Kết quả của tổng A^i là : \n {sumA}')

Câu 5
Kết quả A^2 là : 
 [[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
Kết quả của A^3 là: 
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
Kết quả của tổng A^i là : 
 [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


In [ ]:
#Bài tập Chương 3
print('Câu 1')
print('a.')
import numpy as np
print('Cho ma trận:')
A = np.array([[1, -1, 0], [1, 2, 3], [2, -2, 3]])
print(A)
detA = np.linalg.det(A)
print(f'detA = : {detA}')
if detA == 0:
  print(f'Vì ma trận A = 0 nên ma trận A không nghịch đảo')
else:
  print(f'Vì detA = {detA} ≠ 0 nên ma trận A khả nghịch.')
print('b. ')
print('Họ và tên: Đặng Thị Trúc Đào')
print('c. ')
print('Chuỗi cần mã hóa là: \n 12 07 04 21 15 05 29 16 17 04 05 29 27 30 00 10 05 12 06 01 22')
print('d. ')
print('Ma trận giả định là: ')
mtgd = np.array([[1, 1, 0], [2, 1, 1], [-1, 0, -1]])
print(mtgd)
print('Giải mã hóa')
A1 = np.array([12, 7, 4])
kq1 = np.dot(A1,mtgd)
print(kq1)
A2 = np.array([21, 15, 5])
kq2 = np.dot(A2,mtgd)
print(kq2)
A3 = np.array([29, 16, 17])
kq3 = np.dot(A3,mtgd)
print(kq3)
A4 = np.array([4, 5, 29])
kq4 = np.dot(A4,mtgd)
print(kq4)
A5 = np.array([27, 30, 0])
kq5 = np.dot(A5,mtgd)
print(kq5)
A6 = np.array([10, 5, 12])
kq6 = np.dot(A6,mtgd)
print(kq6)

Câu 1
a.
Cho ma trận:
[[ 1 -1  0]
 [ 1  2  3]
 [ 2 -2  3]]
detA = : 8.999999999999998
Vì detA = 8.999999999999998 ≠ 0 nên ma trận A khả nghịch.
b. 
Họ và tên: Đặng Thị Trúc Đào
c. 
Chuỗi cần mã hóa là: 
 12 07 04 21 15 05 29 16 17 04 05 29 27 30 00 10 05 12 06 01 22
d. 
Ma trận giả định là: 
[[ 1  1  0]
 [ 2  1  1]
 [-1  0 -1]]
Giải mã hóa
[22 19  3]
[46 36 10]
[44 45 -1]
[-15   9 -24]
[87 57 30]
[ 8 15 -7]


In [ ]:
print('Câu 2')
print('a. ')
import numpy as np
n = int(input("Nhập số lượng phần tử c: "))
c = []
for i in range(n):
    x = int(input(f"c[{i}] = "))
    c.append(x)
# Ma trận đơn vị
M = np.eye(2, dtype=int)
# Nhân các ma trận
for x in c:
    A = np.array([
        [x, 1],
        [1, 0]
    ])
    M = np.dot(M, A)
# Lấy pn và qn
pn = M[0, 0]
qn = M[1, 0]
print("\nMa trận kết quả:")
print(M)
print("pn =", pn)
print("qn =", qn)
print(f"\nPhân số thu được: {pn}/{qn}")

Câu 2
a. 
Nhập số lượng phần tử c: 3
c[0] = 3
c[1] = 1
c[2] = 2

Ma trận kết quả:
[[11  4]
 [ 3  1]]
pn = 11
qn = 3

Phân số thu được: 11/3
